"""adding atributes to liked_movies and liked_series tables

Revision ID: 525c8d86190f
Revises: 017d4949d267
Create Date: 2024-06-18 10:25:39.760738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525c8d86190f'
down_revision: Union[str, None] = '017d4949d267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_movies', sa.Column('poster_path', sa.String(), nullable=False))
    op.add_column('liked_movies', sa.Column('release_date', sa.String(), nullable=False))
    op.add_column('liked_series', sa.Column('poster_path', sa.String(), nullable=False))
    op.add_column('liked_series', sa.Column('first_air_date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liked_series', 'first_air_date')
    op.drop_column('liked_series', 'poster_path')
    op.drop_column('liked_movies', 'release_date')
    op.drop_column('liked_movies', 'poster_path')
    # ### end Alembic commands ###
